### ISSUE TITLE
Dirty directory prevents checkout

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/PacBioTestData#28]
```
[SYS] git -C PacBioTestData fetch origin
From ssh://bitbucket.nanofluidics.com:7999/sat/pacbiotestdata
   8743273..450d5f0  master     -> origin/master
[SYS] `git -C PacBioTestData checkout 450d5f04746b75b347bd9ef5e988c1ae6e022d8d`
[INFO] [0]cd '/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis' back from '/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/../pi'
Traceback (most recent call last):
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/pb-git/pb-git", line 80, in <module>
    main(sys.argv)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/pb-git/pb-git", line 78, in main
    args.func(args)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/pb-git/pb_git/cmds.py", line 358, in checkout
    checkout_repo(cfg, args.mirrors)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/pb-git/pb_git/cmds.py", line 347, in checkout_repo
    _checkout_repo(conf, mirrors_base)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/pb-git/pb_git/cmds.py", line 334, in _checkout_repo
    checkout_repo_from_url(url, sha1, 'origin', path)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/pb-git/pb_git/cmds.py", line 202, in checkout_repo_from_url
    out, err = capture(checkout_cmd, log=mylog)
  File "/home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/pb-git/pb_git/cmds.py", line 76, in capture
    raise IOError(err)
IOError: error: Your local changes to the following files would be overwritten by checkout:
        data/HdfSubreadSet/m140912_020930_00114_c100702482550000001823141103261590_s1_p0.1.bax.h5
        data/HdfSubreadSet/m140912_020930_00114_c100702482550000001823141103261590_s1_p0.2.bax.h5
        data/HdfSubreadSet/m140912_020930_00114_c100702482550000001823141103261590_s1_p0.3.bax.h5
        data/HdfSubreadSet/m140912_020930_00114_c100702482550000001823141103261590_s1_p0.bas.h5
Please, commit your changes or stash them before you can switch branches.
Aborting

Failed: /home/UNIXHOME/cdunn/repo/pb/pf/smrtanalysis/bioinformatics/ext/bin/pi-sync
```
I think the `.gitignore` needed whatever was added by git-lfs. But moving forward, if anyone sees this, they can simply remove the directory tree and re-clone. Just noting the failure mode. Feel free to close this Issue.

**Comment by natechols** [comment]
I think getting rid of git-lfs will have fixed this.
